insert into attackitem (name, rarity, speed, attack, description, job) values ('Peck', 'Rare', 9, 876, 'A default attack item by the system!', 'Ninja');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Honed Javelin', 'Common', 4, 175, 'A default attack item by the system!', 'Archer');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Ricochet', 'Rare', 11, 182, 'A default attack item by the system!', 'Warrior');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Dash', 'Common', 5, 164, 'A default attack item by the system!', 'Archer');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Rigormortis', 'Common', 29, 277, 'A default attack item by the system!', 'Archer');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Windtalker', 'Legendary', 42, 530, 'A default attack item by the system!', 'Archer');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Ebon Warbow', 'Legendary', 2, 2055, 'A default attack item by the system!', 'Ninja');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Titanium Speargun', 'Mythic', 28, 513, 'A default attack item by the system!', 'Warrior');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Snitch', 'Common', 29, 79, 'A default attack item by the system!', 'Ninja');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Razorwind', 'Common', 13, 136, 'A default attack item by the system!', 'Rogue');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Eagle', 'Legendary', 4, 1330, 'A default attack item by the system!', 'Ninja');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Prick and Stick', 'Common', 23, 157, 'A default attack item by the system!', 'Rogue');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Alpha and Omega', 'Common', 29, 431, 'A default attack item by the system!', 'Ninja');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Prayer and Curse', 'Mythic', 7, 120, 'A default attack item by the system!', 'Ninja');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Trip and Trap', 'Mythic', 24, 840, 'A default attack item by the system!', 'Ninja');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Hurt and Deceit', 'Rare', 5, 820, 'A default attack item by the system!', 'Ninja');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Thirst and Hunger', 'Common', 1, 292, 'A default attack item by the system!', 'Ninja');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Thorn and Bloom', 'Rare', 2, 152, 'A default attack item by the system!', 'Rogue');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Confuse and Confound', 'Common', 19, 463, 'A default attack item by the system!', 'Rogue');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Clean and Clear', 'Rare', 29, 966, 'A default attack item by the system!', 'Archer');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Corroded Claw', 'Legendary', 60, 510, 'A default attack item by the system!', 'Archer');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Faceplant', 'Common', 22, 397, 'A default attack item by the system!', 'Ninja');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Insanity', 'Legendary', 30, 935, 'A default attack item by the system!', 'Archer');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Venom Fangs', 'Common', 28, 94, 'A default attack item by the system!', 'Rogue');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Seethe', 'Mythic', 9, 1341, 'A default attack item by the system!', 'Archer');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Desolation', 'Legendary', 52, 1645, 'A default attack item by the system!', 'Warrior');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Wit''s End', 'Legendary', 60, 1345, 'A default attack item by the system!', 'Archer');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Deluded Spellblade', 'Mythic', 7, 1206, 'A default attack item by the system!', 'Warrior');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Legionnaire''s Sword', 'Common', 25, 489, 'A default attack item by the system!', 'Warrior');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Wolf', 'Common', 15, 239, 'A default attack item by the system!', 'Warrior');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Darkheart', 'Mythic', 8, 366, 'A default attack item by the system!', 'Archer');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Knightfall', 'Legendary', 60, 2445, 'A default attack item by the system!', 'Archer');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Trinity', 'Rare', 2, 54, 'A default attack item by the system!', 'Archer');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Lament', 'Mythic', 13, 141, 'A default attack item by the system!', 'Warrior');
insert into attackitem (name, rarity, speed, attack, description, job) values ('Scar', 'Rare', 5, 350, 'A default attack item by the system!', 'Rogue');
