insert into defenseitem (name, rarity, defense, gear, description, job) values ('Protection of Fortune', 'Common', 171, 'Helmet', 'A default defense item by the system!', 'Ninja');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Dragon Scaled Crown', 'Rare', 482, 'Boots', 'A default defense item by the system!', 'Warrior');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Jaws of Distant Sorrow', 'Legendary', 845, 'Helmet', 'A default defense item by the system!', 'Ninja');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Holy Iron Helmet', 'Common', 371, 'Shield', 'A default defense item by the system!', 'Rogue');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Edge of Justice', 'Common', 121, 'Helmet', 'A default defense item by the system!', 'Ninja');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Bandit''s Wool Mask', 'Legendary', 775, 'Gauntlets', 'A default defense item by the system!', 'Ninja');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Burden of Prayers', 'Legendary', 2485, 'Boots', 'A default defense item by the system!', 'Warrior');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Pact of Truths', 'Rare', 998, 'Boots', 'A default defense item by the system!', 'Warrior');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Shepherd of Deception', 'Legendary', 530, 'Suit', 'A default defense item by the system!', 'Warrior');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Tribute of Salvation', 'Legendary', 1900, 'Suit', 'A default defense item by the system!', 'Rogue');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Sinister Silver Cuirass', 'Legendary', 1790, 'Suit', 'A default defense item by the system!', 'Ninja');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Vicious Mail Cuirass', 'Legendary', 55, 'Gauntlets', 'A default defense item by the system!', 'Archer');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Baneful Cloak of the Moon', 'Mythic', 81, 'Shield', 'A default defense item by the system!', 'Archer');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Hope''s Cloth Cape', 'Mythic', 993, 'Helmet', 'A default defense item by the system!', 'Rogue');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Victor Linen Wrap', 'Common', 85, 'Suit', 'A default defense item by the system!', 'Ninja');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Wrap of Shattered Magic', 'Mythic', 1017, 'Boots', 'A default defense item by the system!', 'Warrior');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Mantle of Distant Souls', 'Mythic', 801, 'Boots', 'A default defense item by the system!', 'Warrior');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Gloves of Fire Magic', 'Rare', 662, 'Helmet', 'A default defense item by the system!', 'Ninja');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Hands of Condemned Protection', 'Common', 231, 'Suit', 'A default defense item by the system!', 'Archer');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Gauntlets of Holy Illusions', 'Common', 462, 'Gauntlets', 'A default defense item by the system!', 'Rogue');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Grips of Demonic Fire', 'Common', 27, 'Boots', 'A default defense item by the system!', 'Ninja');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Grips of Ending Fortune', 'Rare', 756, 'Helmet', 'A default defense item by the system!', 'Archer');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Walkers of Infinite Wars', 'Legendary', 1360, 'Gauntlets', 'A default defense item by the system!', 'Ninja');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Walkers of Unholy Glory', 'Rare', 54, 'Gauntlets', 'A default defense item by the system!', 'Archer');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Sabatons of Frozen Worlds', 'Mythic', 963, 'Boots', 'A default defense item by the system!', 'Ninja');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Boots of Frozen Fires', 'Mythic', 969, 'Shield', 'A default defense item by the system!', 'Archer');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Storm Breaker', 'Common', 54, 'Shield', 'A default defense item by the system!', 'Ninja');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Purifier', 'Rare', 268, 'Helmet', 'A default defense item by the system!', 'Warrior');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('The Barricade', 'Mythic', 342, 'Shield', 'A default defense item by the system!', 'Archer');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Malice', 'Legendary', 830, 'Suit', 'A default defense item by the system!', 'Ninja');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('King''s Legacy', 'Common', 384, 'Shield', 'A default defense item by the system!', 'Rogue');
insert into defenseitem (name, rarity, defense, gear, description, job) values ('Treads of Distant Hope', 'Legendary', 1310, 'Shield', 'A default defense item by the system!', 'Ninja');
